### ISSUE TITLE
Decorator option for sync/threaded

### ISSUE THREAD

**Issue by Bartvds** [defrex/django-after-response#3]
Would be cool if the decorator could override the async option, so we can optimise for both safe and unsafe tasks.

**Comment by defrex** [comment]
Can you elaborate on what you mean? Perhaps with some mock code.

**Comment by Bartvds** [comment]
Something like:

````py
@after_response.enable(async=True)
def my_task(arg1, arg2):
    # threadsafe code

@after_response.enable(async=False)
def my_other_task(arg1, arg2):
    # unsafe code
````

**Comment by defrex** [comment]
Perhaps this should be better documented, but when async is off, the request still waits for the function to complete before closing. The reason I added it as a settings was for debugging, which is much simpler when threading is disabled.

So while this option would be easy to add, it would be equivalent to using Django's built-in `request_finished` signal. I recommend using that.
