### ISSUE TITLE
Adaptation for progress bar?

### ISSUE THREAD

**Issue by grwhumphries** [defrex/django-after-response#7]
Hey there

Is there any way this could be adapted to create a progress bar? 

for example, if one were to have a large function running, after_response would send a value out for jquery or ajax call to ingest at every iteration of a loop?

Cheers

**Comment by defrex** [comment]
You _could_ devise a way to make a progress bar using after-response. You'd have to store your progress somewhere, like a file, cache or database. Then have an HTTP endpoint that looked up that value, returning it to the client.

Alternately, you could try to get something working using a streaming response, which Django supports. Perform your task synchronously in the normal request handler, and stream a bit of data back as progress is completed.

Or thirdly, use websockets. Though, the Django support for that won't be awesome for another version or two.

**Comment by defrex** [comment]
All that said, there is no explicit support for progress reporting that makes sense in after-response, so I'm going to close this ticket.
